version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: business_manager_db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  tomcat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tomcat-container
    depends_on:
      - mysql
    ports:
      - "8080:8080"
      - "80:80"
      - "443:443" 
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge
